TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument

Documentation/WritingReST/Introduction.rst

the origin link has changed:
- www.sphinx-doc.org/en/stable/.. no longer exists and will be forwarded to 
- www.sphinx-doc.org/en/master/.. where page /markup is not found
I recommend to use the last stable version number, instead. I could not found a better way to avoid specific version number.
If newer versions are available, it is written so in header of the page. For example see: www.sphinx-doc.org/en/1.4.9/markup/

Fix changed link for sphinx-doc.org and url sheme

---

Documentation/WritingReST/Introduction.rst

the origin url has changed:
- www.sphinx-doc.org/en/stable/.. no longer exists and will be forwarded to 
- www.sphinx-doc.org/en/master/.. where page /markup is not found
I recommend to use the last stable version number, instead. I could not found a better way to avoid specific version number.
If newer versions are available, it is written so in header of the page. For example see: www.sphinx-doc.org/en/1.4.9/markup/
Use HTTPS instead of HTTP

Fix changed url for sphinx-doc.org and url sheme

---

Documentation/RenderingDocs/Index.rst
Documentation/RenderingDocs/Quickstart.rst

In order to streamline information and reduce duplicate documentation
in several places: remove information about rendering with Docker
to a link to the Docker Render Documentation Readme on GitHub
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/58

Replace Docker render information with link to GitHub Readme

---

Documentation/Index.rst
Documentation/TipOfTheDay.rst
Documentation/WritingDocForExtension/CreateFromScratch.rst
Documentation/WritingDocForExtension/ExtensionAuthorTips.rst

- the tip has moved from homepage to this guide: fix link
- add information that it's about a starter project to title
- move tip from general tips to tips for extension authors

Fix information for tip: how to start documentation for your extension

---

Documentation/WritingDocsOfficial/GithubMethod.rst
Documentation/WritingDocsOfficial/Index.rst
Documentation/WritingDocsOfficial/LocalEditing.rst
Documentation/WritingDocsOfficial/WorkflowMethods.rst

In the past, we had the description of the "Edit me on GitHub" workflow on
the start page of the Contribution chapter. This might result in people
being pushed towards this workflow. And it may be confusing not to
make clear there are 2 different workflows straight up front.
This commit:
- describes the workflows first
- clearly labels and numbers subchapters

Restructure contribution workflows

---

Documentation/RenderingDocs/Quickstart.rst

- 'dockrun_t3rdf' not found
- 'dockrun_t3rd' is fine

Remove trailing 'f' form 'dockrun_t3rd'

---

Documentation/GeneralConventions/DirectoryFilenames.rst
Documentation/WritingDocForExtension/Index.rst
Documentation/WritingDocForExtension/Migrate.rst

* Provide full valid example of composer.json for TYPO3 extensions.
* Provide new section for migrating existing documentation.

Document changes to docs.typo3.org

---

Documentation/RenderingDocs/Quickstart.rst

On some Macs, the source command will fail. Therefore an alternative method is provided.

Add alternative method for documentation rendering

---

Documentation/RenderingDocs/Index.rst

The starter projects are no longer available on the documentation server.

Replace starter project method with documentation-draft

---

Documentation/WritingDocForExtension/FAQ.rst
Documentation/WritingDocForExtension/Index.rst
Documentation/WritingDocForExtension/Migrate.rst

* Do not repeat the same information multiple times. That would make it
much harder to maintain those information.
* Split information into multiple sections. Migration should just be
about migration. FAQ should be FAQ and easier to find.
* Do not mention how to register for slack multiple times, just once.
Also the team page already has those information. There is no need to
duplicate them in the same context.
* Remove intercept from migration. That's already part of Webhook
workflow anyway, leading to duplicate information and bloated number
of steps for migration.
* Remove known issues, as this is already covered by FAQ and duplicates
information.

Streamline documentation

---

Documentation/WritingDocsOfficial/LocalEditing.rst

- In the official documenation, all repos were switched to "master"

Remove reference to "latest" branch

---

Documentation/WritingDocForExtension/Webhook.rst

Some fixes, changes for clarity and removal of superfluous text
- shorten text
- add comma
- replace word
- move new important block down so that section about the hosters is not split up. 
- replace for "in those systems" for more clarity
- remove "An update is required". Sentence seemed a little vague and not really clear (as if another step is required) and not necessary. All people need to know: legacy webhook -> no longer supported, use new webhook.
- Add extra text (For the documentation to be rendered ...) to creation of GitHub hook as well (because it already existed in the description for bitbucket and gitlab).

Minor language improvements

---

Documentation/GeneralConventions/Index.rst
Documentation/Index.rst

- rename to "Documentation content style guide"
- add the most important conventions to start page
- move "How to update for new releases" to "Advanced" section

Improve start page of conventions

---

Documentation/Index.rst

The new theme will make blockquotes visible. So there may be some places where blockquotes were used because they came in handy to indent things. This is how the new theme would show the page:

Remove blockquote style

---

Documentation/RenderingDocs/RenderWithDockerCompose.rst

There is no reason to use version 2 anymore.

Suggest Docker Compose version 3

---

Documentation/WritingDocForExtension/ReregisterVersions.rst

Also document invocation via `sh`.
An alternative would be to document
`chmod +x trigger_documentation_push.sh`,
but `sh` prefix is more straight forward.

Fix typo in trigger_documentation_push.sh example

---

Documentation/WritingReST/DefinitionLists.rst

on https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/DefinitionLists.html#example-2-nicely-styled
some code examples are styled as quotes

Remove unneded indentation

---

Documentation/GeneralConventions/Glossary.rst

According to here: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/ContentStyleGuide.html#exceptions-for-specific-typo3-spellings and most other documentation ViewHelper should be written in CamelCase. If it was not it would have to be written in two word: view helper.  What do you think?

Write ViewHelper in CamelCase

---

Documentation/GeneralConventions/HowToUpdateDocs.rst

Should we display version hints? #14 is closed and decided, Therefore remove it from work in progress

Remove refernece to issue "display version hints?"

---

Documentation/BasicPrinciples.rst
Documentation/GeneralConventions/DirectoryFilenames.rst
Documentation/GeneralConventions/ExampleTexts.rst
Documentation/GeneralConventions/Index.rst
Documentation/GeneralConventions/Licenses.rst

Issues:
Resolves: TYPO3-Documentation/T3DocTeam#151
Related: TYPO3-Documentation/T3DocTeam#6
Related: TYPO3-Documentation/T3DocTeam#132
Related: TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual#24
Related: TYPO3-Documentation/T3DocTeam#89
Related: TYPO3-Documentation/T3DocTeam#88
Related: TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual#12
Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#40
Related: TYPO3-Documentation/T3DocTeam#6
PR:
Related: TYPO3-Documentation/TYPO3CMS-Reference-TCA#330
See also decision: https://decisions.typo3.org/t/proposal-for-documentation-manual-start-page/668

Add text for example start page

---

Documentation/GeneralConventions/ExampleTexts.rst

Sitemap is in menu. However, if the menu is very long and cluttered (as in "TYPO3 Explained", it might still be a good idea to have a link to the siteamp (or the index, if it exists) on the start page.

Remove requirement for sitemap link on start page

---

Documentation/WritingDocsOfficial/Index.rst

Since this is THE start page for contribution and people may often
look for information besides just the workflow.

Add quick links to contribution page

---

Documentation/WritingDocsOfficial/GithubMethod.rst
Documentation/WritingDocsOfficial/Index.rst
Documentation/WritingDocsOfficial/LocalEditing.rst

The intent of this commit it to better explain how users can contribute to the TYPO3 documentation either by editing pages on GitHub or by pulling down a repository and making the changes locally.

Improve overall readability of "How To Contribute" chapter

---

Documentation/WritingDocForExtension/ReregisterVersions.rst

Move the sleep before remote deletion.
Intercept might try to render an already removed branch.
Therefore, give intercept a chance to render before deletion.

Make re register more robust

---

Documentation/BasicPrinciples.rst

The main TYPO3 repository changed - adjust URLs accordingly.

[TASK] Update repository URL

---

Documentation/WritingReST/CheatSheet.rst
Documentation/WritingReST/Hyperlinks.rst

See TYPO3-Documentation/T3DocTeam#164 for details.

[TASK] Disable all dummy urls with `:samp:`

---

Documentation/WritingDocForExtension/FAQ.rst

We often get asked how long it takes until new documentation is linked from extensions.typo3.org.
This entry explains what's happening and how long it might take.

Add FAQ Entry regarding link from extensions to docs

---

Documentation/WritingReST/CheatSheet.rst
Documentation/WritingReST/Codeblocks.rst
Documentation/WritingReST/Hyperlinks.rst

See TYPO3-Documentation/T3DocTeam#165 for details.
This repository was missing in the first run.

[TASK] Unify top-level domain of dummy urls

---

Documentation/BasicPrinciples.rst
Documentation/Changes.rst
Documentation/GeneralConventions/DirectoryFilenames.rst
Documentation/GeneralConventions/ExampleTexts.rst
Documentation/Maintainers/BackportChanges.rst
Documentation/Settings.cfg
Documentation/WritingDocForExtension/FAQ.rst
Documentation/WritingDocForExtension/Index.rst
Documentation/WritingDocsOfficial/HowYouCanHelp.rst
Documentation/WritingDocsOfficial/LocalEditing.rst
Documentation/WritingReST/CheatSheet.rst
Documentation/WritingReST/Codeblocks.rst
Documentation/WritingReST/CodingGuidelines.rst
Documentation/WritingReST/CommonPitfalls/Indents.rst
Documentation/WritingReST/Graphs.rst
Documentation/WritingReST/Reference.rst

This is how it looks like, as soon as the [default Graphviz styles](https://github.com/t3docs/docker-render-documentation/pull/123) have been merged into the rendering docker image.
Related to: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/252

Add Graphviz graphs docs

---

Documentation/BasicPrinciples.rst
Documentation/GeneralConventions/ReviewInformation.rst
Documentation/WritingReST/BasicRestSyntax.rst

and references to the non-existant typo3 wiki
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/170
releases: main

[TASK] Remove old wiki links

---

Documentation/About.rst

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/170 for details.

[TASK] Mark TYPO3 Wiki as retired

---

Documentation/GeneralConventions/FileStructure.rst

In code blocks `.. code-block:: ts` is used for typescript as a sphinx standard. code-blocks with code-type ts may therefore not contain typoscript or code highlighting will fail. the practice of using `:ts:` for inline code-blocks creates an unnecessary confusion as ppl will then also use it for code-blocks. This has caused missing syntax highlighting and rendering warnings throughout the different documentations.
Unfortunary I didn't catch this in the first review of this document

Lets not use :ts: for typoscript

---

Documentation/GeneralConventions/FileStructure.rst

This PR is a follow-up of PR #266 and updates the recently introduced [TYPO3 documentation standards](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html) with standards that have been created during the standard runs across many manuals of the TYPO3 community, see
* https://github.com/TYPO3-Documentation/T3DocTeam/issues/181
* https://github.com/TYPO3-Documentation/T3DocTeam/issues/182
* https://github.com/TYPO3-Documentation/T3DocTeam/issues/185
Fixes: #274

[DOCS] Update TYPO3 documentation standards

---

Documentation/BasicPrinciples.rst
Documentation/Index.rst
Documentation/UserRoundTrip.rst

After having created and published the project's documentation, a navigation should be set up that guides the project user across documentation, code repository and Packagist and TER pages.
Fixes: #280

[DOCS] Integrate new page "User's round trip"

---

Documentation/GeneralConventions/FileStructure.rst

In production the TYPO3 system extensions use the same title pattern as the third-party extensions: reflect it in the documentation standard.
Relates: https://forge.typo3.org/issues/97258

[DOCS] Align title of system and third-party extension

---

Documentation/GeneralConventions/Index.rst

Module names on first level are written in title case nowadays.
The empty line was inserted because PhpStorm complained about the missing empty line.

[TASK] Streamline guilabel example

---

Documentation/BasicPrinciples.rst

Also the title of part 3 of the series was updated (also not linked as
it is outdated).
See: https://typo3worx.eu/2017/02/guide-to-typo3-documentation-part-3-contribute/

[TASK] Avoid capitalized link texts

---

.editorconfig
Documentation/GeneralConventions/CodingGuidelines.rst
Documentation/WritingDocsOfficial/GithubMethod.rst
Documentation/WritingReST/BasicRestSyntax.rst
Documentation/WritingReST/CheatSheet.rst
Documentation/WritingReST/Codeblocks.rst
Documentation/WritingReST/CommonPitfalls/Indents.rst
Documentation/WritingReST/Images.rst
Documentation/WritingReST/Lists.rst

To prevent separate text changes from syntax changes the examples have not been updated yet. will do that in a follow up
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/194

Change default rst indentation to 4 spaces

---

Documentation/GeneralConventions/CodingGuidelines.rst

refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/194

Change editorconfig to use 4 spaces

---

Documentation/Appendix/ExampleTocTree/Index.rst
Documentation/Appendix/ExampleTocTree/Topic1/Index.rst
Documentation/Appendix/ExampleTocTree/Topic1/Subtopic1.rst
Documentation/Appendix/ExampleTocTree/Topic1/Subtopic2.rst
Documentation/GeneralConventions/CommitMessages.rst
Documentation/GeneralConventions/ContentStyleGuide.rst
Documentation/GeneralConventions/Format.rst
Documentation/WritingReST/CheatSheet.rst
Documentation/WritingReST/CommonPitfalls/Headers.rst
Documentation/WritingReST/CommonPitfalls/Hyperlinks.rst
Documentation/WritingReST/CommonPitfalls/Indents.rst
Documentation/WritingReST/CommonPitfalls/InlineStyle.rst
Documentation/WritingReST/CommonPitfalls/Lists.rst
Documentation/WritingReST/Reference/Code/Codeblocks.rst
Documentation/WritingReST/Reference/Content/BoldItalic.rst
Documentation/WritingReST/Reference/Content/Links.rst
Documentation/WritingReST/Reference/Content/SpecialCharacters.rst
Documentation/WritingReST/Reference/Graphics/Index.rst

We always use explicit code-blocks

Removed all remains of litteral blocks (::) and highlight directive

---

Documentation/WritingReST/CheatSheet.rst

Additionally, correct tip about position of "View source" link.

[BUGFIX] Avoid quote style in admonition section

---

Documentation/BasicPrinciples.rst
Documentation/GeneralConventions/HowToUpdateDocs.rst
Documentation/GeneralConventions/ReviewInformation.rst
Documentation/GitHub/Index.rst
Documentation/RenderingDocs/RenderWithDockerCompose.rst
Documentation/WritingDocForExtension/ContributeToSystemExtension.rst
Documentation/WritingDocsOfficial/GithubMethod.rst
Documentation/WritingDocsOfficial/HowYouCanHelp.rst

We now use the start label again to link to start pages
Related: TYPO3-Documentation/T3DocTeam#198

Replace links to start page (:doc: => :ref:)

---

Documentation/RenderingDocs/Quickstart.rst

The docker images are hosted on github now. Explanation on how to pull them from there are added

[TASK] add information about new docker-image repository

---

Documentation/RenderingDocs/Quickstart.rst

The image used in the second step is now the pulled one from first step.

Change Docker-Image in source command to the pulled one

---

Documentation/RenderingDocs/Index.rst

[How to render documentation](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/RenderingDocs/Index.html) has a broken list. 
After the second step, the code block is shown as quote block and the next step starts at number one again, but should be number three.
This was solved by fixing the indent of the code block, which was previously three spaces instead of four.

Fixed How to render documentation numbered list by correcting indent

---

Documentation/WritingReST/CheatSheet.rst

(These are used in the TYPO3 core, so I hope they are available everywhere?)

[DOCS] Update CheatSheet to also showcase bash,sql,xml code highlight

---

Documentation/Maintainers/BackportChanges.rst

This solves the following warning on rendering:
./Documentation/Maintainers/BackportChanges.rst:122: ERROR: Unknown interpreted text role "shell".

[BUGFIX] Avoid warning of unavailable text role "shell"

---

Documentation/WritingReST/Reference/Code/Phpdomain.rst

The ContextAwareTrait has been removed with TYPO3 v13. Therefore, we should not use this trait as an example. It is replaced by the Psr\Log\LoggerAwareTrait.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/767

[TASK] Remove ContextAwareTrait in favor of LoggerAwareTrait

---

Documentation/GeneralConventions/FileStructure.rst

prune unnecessary information.
Depends on https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/367

[TASK] Reduce single file documentation / README

---

CONTRIBUTING.rst
Makefile

This is more convenient then having to copy-paste the command all the time

[TASK] Introduce Makefile and command 'make docs'

---

Documentation/GeneralConventions/FileStructure.rst
Documentation/Index.rst
Documentation/genindex.rst

It was not really usefull and does not work in the new rendering. We will use the indexes to enhance the elastic search instead

[TASK] Remove genindex

---

Documentation/WritingDocsOfficial/LocalEditing.rst

Correct the headline, this is really an introduction to GitHub and does not explain how to render with Docker. Link to rendering with Docker page. Correct indentation, introduce GitHub Organization as entry point

[TASK] Overhaul local editing

---

Documentation/BasicPrinciples.rst
Documentation/WritingDocForExtension/ContributeToSystemExtension.rst

we had so much, rather insignificant, content here that probably no one was reading it.

[TASK] Overhaul and shorten "Basic Principles"

---

Documentation/WritingDocForExtension/ContributeToSystemExtension.rst

It is mainly explained in the Core contribution guide

[TASK] Overhaul and shorten "Contribute to system extensions"

---

Documentation/WritingReST/Reference/Content/Admonitions.rst

For the word _attention_, the article "an" is used, instead of "a", because _attention_ starts with a vowel.

use correct article for the word attention

---

Documentation/GeneralConventions/GuidesXml.rst

Follow-up to https://github.com/TYPO3-Documentation/render-guides/pull/498
This adds the link to the list of interlink inventories available by default.

[TASK] Add link to render-guides list of default inventories

---

Documentation/WritingReST/Reference/Content/Cards.rst

Make using container for the card deprecated

[FEATURE] Explain how to use card directives

---

Documentation/Index.rst

- use card directives instead of container directives
- use more helpful cards

[TASK] Overhaul start page

---

Documentation/WritingReST/Reference/Code/Index.rst
Documentation/WritingReST/Reference/Graphics/Index.rst

They cause warnings since the newest version of the render-guides

[BUGFIX] Resolve duplicate link anchors

---

Documentation/WritingReST/CheatSheet.rst

The example still uses the Settings.cfg,. But the text already explains the guides.xml.

use guides.xml inventory

---

Documentation/Migration/Index.rst
Documentation/RenderingDocs/Index.rst
Documentation/WritingReST/Reference/Code/Confval.rst

My "pet project" typo3-documentation-browsersync is in a state where I'd like to collect some feedback, also to see if in the end this project might be movable to the TYPO3-Documentation repository.
For that I've created a small documentation on how to use it, hopefully also a base to present it for the T3DD24 in the scope of Linas talk presenting render-guides.
(This also drive-by-fixes an issue with a missing literalainclude syntax for _Makefile that removes a warning from rendering. Another issue is still open that causes the rendering to fail with a duplicate RST header, which is beyond the scope of this PR)

[TASK] Add reference to typo3-documentation-rendersync project

---

Documentation/GeneralConventions/Glossary.rst

TYPO3 has its own rules, so let's respect upper/lowercasing from others as well :-)
Follow-up to https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4509#discussion_r1632168380

[TASK] Enhance glossary by specific product names

---

Documentation/GeneralConventions/_guides-simple.xml

Add attribute `project_discussions`, as a corresponding GitHub page exists in the context of the news extension from the example.

[TASK] Add missing attribute `project_discussions`

---

Documentation/Migration/Index.rst

Make the reason for creating the file Makefile more apparent. Try to keep the central idea of a Makefile and how it fits into the whole context.

[DOCS] Rearrange Makefile sections and local rendering

---

.github/workflows/documentation.yml
Documentation/Howto/RenderingDocs/Index.rst
Documentation/_CodeSnippets/_Makefile
Documentation/_CodeSnippets/_documentation.yml
Makefile

This allows us to control specific settings needed for mininmal tests (like setting only a single output format) or more for the future.
See also: https://github.com/TYPO3-Documentation/render-guides/pull/765

[TASK] Use --minimal-test CLI option for documentation tests

---

Documentation/Howto/Migration/Index.rst

use guides.xml instead of yaml

[DOC] correct wrongly used filename

---

Documentation/Reference/GuidesXml.rst

[TASK] Use proper dash notation

---

Documentation/Basics/GeneralConventions/Format.rst
Documentation/Howto/Migration/Index.rst
Documentation/Maintainers/Tools.rst
Documentation/Reference/ReStructuredText/Code/Phpdomain.rst

- Improve note about automated migration
- Removed some references to sphinx

[TASK] cleanup docs

---

Documentation/_Includes/_LocalRendering.rst.txt

The folder is automatically created now, the file can just be opened in any browser.

[TASK] Adjust local rendering

---

Documentation/Howto/Migration/Index.rst
Documentation/Howto/Migration/MarkdownToReST.rst

This is a basic description how to use render-guides to convert markdown to ReST.

[TASK] document how to migrate to rst

---

Documentation/Reference/ReStructuredText/Code/Phpdomain.rst

The directive doesn't exist, as discussed in Slack: https://typo3.slack.com/archives/C028JEPJL/p1737711998088519?thread_ts=1737710334.087189&cid=C028JEPJL

[BUGFIX] Remove mention of php:currentnamespace::

---

Documentation/Maintainers/BackportChanges.rst

I thought it might help to add some hints what has to be done in case a merge conflict arises.

[DOCS] Add hints when merge conflict arises during manual backport

---

Documentation/Advanced/GuidelinesForImages.rst

as the readme file changed, the link must be adopted

[TASK] Update link
