Documentation/WritingReST/Hyperlinks.rst
Adopt changed url from sphinx-doc.org, change sheme from http to https
=> Fix external link for 302

Documentation/WritingReST/MenuHierarchy.rst
External link has been changed and redirects with 302
Use HTTPS instead of HTTP
=> Fix external link for 302 and url sheme

Documentation/RenderingDocs/Quickstart.rst
External link has been changed and redirects with 301
=> Fix external link for 301

Documentation/GeneralConventions/ContentStyleGuide.rst
Some minor spelling and phrasing issues. 
(IMO, the text still needs to be proof-read by a native speaker.
Personal note: excellent resource, excellent clarification! Congrats to the team!)
=> Fix spelling and phrasing

Documentation/WritingDocsOfficial/LocalEditing.rst
Add the following
- setup Git and SSH key
- keep local repository up-to-date
=> Update page about local editing and rendering

Documentation/GeneralConventions/DirectoryFilenames.rst, Documentation/WritingDocForExtension/CreateFromScratch.rst, Documentation/WritingDocForExtension/Index.rst, Documentation/WritingDocForExtension/Introduction.rst
These are some additional requirements for the new Intercept docs server.
=> [TASK] Add new workflow for new docs server

Documentation/BasicPrinciples.rst, Documentation/WritingDocForExtension/ContributeToSystemExtension.rst, Documentation/WritingDocForExtension/CreateFromScratch.rst, Documentation/WritingDocForExtension/Index.rst, Documentation/WritingDocForExtension/Introduction.rst
- reduce preliminaries
- move "about extensions" to "Basic Principles"
=> Clean up extension section

Documentation/Index.rst, Documentation/TipOfTheDay.rst, Documentation/WritingDocForExtension/ExtensionAuthorTips.rst, Documentation/WritingDocsOfficial/LocalEditing.rst
- add tip
- change step branching out in Git / Docker workflow description
=> Make changes for switch to master

Documentation/GeneralConventions/DirectoryFilenames.rst, Documentation/WritingDocForExtension/Migrate.rst
Add hint to contact team for redirects.
Add hint regarding extension key detection from composer.json
=> Improve migration and composer info

Documentation/Settings.cfg
=> Add extlinks issue to Settings.cfg

Documentation/Appendix/SupportedFilenamesAndFormats.rst, Documentation/GeneralConventions/Format.rst, Documentation/GeneralConventions/Index.rst
Text was previously in "Appendix"
=> Move information about formats to conventions

Documentation/HowToAddTranslation/Index.rst, Documentation/Index.rst
=> Add information about translating a manual

Documentation/About.rst, Documentation/GeneralConventions/Index.rst, Documentation/Index.rst, Documentation/Preface/Index.rst, Documentation/WritingDocForExtension/CreateFromScratch.rst, Documentation/WritingDocForExtension/CreateWithExtensionBuilder.rst, Documentation/WritingDocForExtension/Index.rst, Documentation/WritingDocForExtension/Migrate.rst
- add menu captions for structuring the menu
- separate extension documenting with example manual and extension_builder
=> Minor restructuring

Documentation/GitHub/Index.rst
not everyone writing documentation is using github every day
=> Solve an issue using keywords

Documentation/GeneralConventions/CodingGuidelines.rst, Documentation/GeneralConventions/HowToUpdateDocs.rst, Documentation/GeneralConventions/Index.rst, Documentation/Settings.cfg
- version hints
- link to changelog
- :guilabel:
=> Add more information to "Content Style Guide" summary

Documentation/WritingDocForExtension/Webhook.rst
Also fix indentation for webhook section, which would be displayed
broken due to new theme.
=> Add section about approval step for extension

Documentation/BasicPrinciples.rst, Documentation/GeneralConventions/CodingGuidelines.rst, Documentation/GeneralConventions/CommitMessages.rst, Documentation/GeneralConventions/MenuHierarchy.rst, Documentation/GitHub/Index.rst, Documentation/RenderingDocs/Quickstart.rst, Documentation/RenderingDocs/Troubleshooting.rst, Documentation/WritingContent/Tutorial.rst, Documentation/WritingDocForExtension/FAQ.rst, Documentation/WritingDocsOfficial/LocalEditing.rst, Documentation/WritingReST/BasicRestSyntax.rst, Documentation/WritingReST/CommonPitfalls/Headers.rst
Suggestion to correct many minor spelling mistakes
=> spelling mistakes

Documentation/WritingDocForExtension/Index.rst, Documentation/WritingDocForExtension/Migrate.rst, Documentation/WritingDocForExtension/ReregisterVersions.rst, Documentation/WritingDocForExtension/Webhook.rst
* Add hint about ReregisterVersions during migration steps.
* Add info about workflow when tagging / publishing an extension.
=> Improve documentation regarding migration and current workflow

Documentation/GeneralConventions/Glossary.rst, Documentation/Includes.rst.txt
Explain text role 'pn' and improve usability of page "Spellings, terms and glossary"
=> Update Glossary.rst, add text role 'pn'

Documentation/GeneralConventions/ExampleTexts.rst
Related: TYPO3-Documentation/T3DocTeam#151
=> Add information about link targets

Documentation/WritingDocsOfficial/LocalEditing.rst
Just a minor textual rephrase and update of the link (including anchor)
=> Rephrase reference to GitHub docs

Documentation/BasicPrinciples.rst, Documentation/GeneralConventions/CommitMessages.rst, Documentation/GeneralConventions/ContentStyleGuide.rst, Documentation/GeneralConventions/DirectoryFilenames.rst, Documentation/GeneralConventions/ExampleTexts.rst, Documentation/GeneralConventions/Format.rst, Documentation/GeneralConventions/GuidelinesForImages.rst, Documentation/GeneralConventions/HowToUpdateDocs.rst, Documentation/GeneralConventions/MenuHierarchy.rst, Documentation/GeneralConventions/ReviewInformation.rst, Documentation/GitHub/Index.rst, Documentation/HowToAddTranslation/Index.rst, Documentation/ToolsEditRest/Index.rst, Documentation/WritingDocForExtension/ContributeToThirdPartyExtension.rst, Documentation/WritingDocForExtension/CreateFromScratch.rst, Documentation/WritingDocForExtension/FAQ.rst, Documentation/WritingDocForExtension/Migrate.rst, Documentation/WritingDocForExtension/Webhook.rst, Documentation/WritingDocsOfficial/HowYouCanHelp.rst, Documentation/WritingReST/BasicRestSyntax.rst, Documentation/WritingReST/Hyperlinks.rst, Documentation/WritingReST/Images.rst, Documentation/WritingReST/Tables.rst
=> [TASK] Replace all occurences of e.g." with "for example"

Documentation/BasicPrinciples.rst, Documentation/WritingDocForExtension/ContributeToSystemExtension.rst
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.
=> [TASK] Update TYPO3 repository URL

Documentation/Changes.rst, Documentation/WritingDocForExtension/ReregisterVersions.rst, Documentation/WritingDocsOfficial/LocalEditing.rst
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/162 for details.
=> [TASK] Replace `git@github.com:` by `git://github.com/`

Documentation/Changes.rst, Documentation/WritingDocForExtension/ReregisterVersions.rst, Documentation/WritingDocsOfficial/LocalEditing.rst
See TYPO3-Documentation/T3DocTeam#163 for details.
=> [TASK] Replace `git://github.com/` with `git@github.com:`

Documentation/GeneralConventions/DirectoryFilenames.rst
Should be fixed, see https://github.com/t3docs/docker-render-documentation/issues/64
=> Remove information for problem with single-file solution

Documentation/WritingReST/CheatSheet.rst, Documentation/WritingReST/Hyperlinks.rst
See TYPO3-Documentation/T3DocTeam#165 for details.
=> [TASK] Unify top-level domain of dummy urls - Documentation

Documentation/WritingDocForExtension/Migrate.rst, Documentation/WritingDocForExtension/Webhook.rst, Documentation/WritingReST/CommonPitfalls/Hyperlinks.rst, Documentation/WritingReST/YoutubeVideos.rst
See TYPO3-Documentation/T3DocTeam#166 for details.
=> [TASK] Unify placeholder syntax

Documentation/Index.rst
- Remove otudated information
- Add links to new documentation in "Whats's new in this guide
section"
=> Update start page

Documentation/WritingDocsOfficial/HowYouCanHelp.rst
A link is added to the PlantUML page in "How you can help".
=> Add link to PlantUML page

Documentation/Includes.rst.txt, Documentation/WritingReST/InlineCode.rst
* Add `bash` and `shell` textroles for `code`
* Improve color contrast for all inline styles derived from `code`
=> Update Inline code

Documentation/WritingReST/Admonitions.rst
See https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/169
=> Remove Adminition "important"

Documentation/Changes.rst, Documentation/GeneralConventions/FileStructure.rst, Documentation/WritingReST/Reference/Content/Index.rst, Documentation/WritingReST/Reference/Index.rst
=> Fix rendering warnings

Documentation/WritingReST/Reference/Content/Tables.rst
=> Attention: Avoid using large tables

Documentation/GeneralConventions/Glossary.rst, Documentation/Settings.cfg, Documentation/WritingDocsOfficial/HowYouCanHelp.rst, Documentation/WritingReST/CommonPitfalls/Hyperlinks.rst, Documentation/WritingReST/Reference/Code/Confval.rst
And remove some outdated information or examples of wrong syntax in the doing
=> [TASK] Remove warnings

Documentation/WritingReST/CheatSheet.rst
Sorry, I didn't complete this PR properly, my bad :(
=> [DOCS] Follow-up fix to document xml/php/sql formatting

Documentation/Maintainers/Index.rst, Documentation/Maintainers/NewMajorCoreVersion.rst
This is a starting point to get the doings documented. This is possibly not complete.
=> [FEATURE] Add chapter "New major Core version released"

Documentation/WritingDocForExtension/Migrate.rst
=> [TASK] Adjust migration page

.github/workflows/backport.yml
So that while we are working on two versions
we can do automatic backports via label
=> [TASK] Introduce backport workflow

Documentation/GeneralConventions/FileStructure.rst, Documentation/GeneralConventions/GuidesXml.rst, Documentation/GeneralConventions/_guides-simple.xml, Documentation/WritingDocForExtension/Migrate.rst
I will explain the interlink mapping in depth in a follow up.
=> [FEATURE] Document guides.xml

Documentation/GeneralConventions/GuidesXml.rst, Documentation/GeneralConventions/Index.rst
* Include in the toctree
* Include a table of contents
* Improve the title
=> [TASK] guides.xml chapter improvements

Documentation/CodeSnippets/FileStructure/ReadmeRstStandalone.rst.txt
There is a markdown table which does not work in REST.
=> The REST README must not be in markdown

.editorconfig, Documentation/WritingDocForExtension/Migrate.rst, Documentation/WritingDocForExtension/_Makefile, Documentation/WritingDocForExtension/_documentation.yml, Makefile
Still work in progress, but would be happy if you can check it out fully rendered. Then I can chop this PR up into smaller chunks for reviewing, if I must :D
* Fixes indentation
* Also includes a podman/docker tab (need to disentangle this with the other PR)
* Add more migration steps:
* remove files
* adapt Includes.rst.txt
* genindex (plus notes/todo)
* prevent bad codesnippets
* Explain workflows
* Explain makefile
Not sure about the structure yet, maybe better to have those giant (NUMBERS) and a "table of contents" of the steps? Need to read up on how to do this.
=> [TASK] Add in-depth notes for migration

Documentation/GeneralConventions/Index.rst, Documentation/GeneralConventions/ReviewPolicy.rst, Documentation/WritingDocsOfficial/Index.rst, Documentation/WritingDocsOfficial/LocalEditing.rst
As promised in our last team meeting, I tried to put https://docs.google.com/document/d/1iPQDoGe646r7vqCvgYC11CkwArpZfNT2Xzj2P42Saj4/edit#heading=h.7277wo2jsthg into this manual.
This has not yet been proof-read and is a first version. Please tell me if we're on track with this.
=> [TASK] Put the new "Review Policy" into writing

Documentation/GeneralConventions/Glossary.rst
This adds a crosslink to the actual Terminology and unifies/streamlines some formatting
=> [TASK] Streamline terminology, crosslink

Documentation/Reference/FileStructure.rst, Documentation/Reference/_FileStructure/_Includes.rst.txt
Resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/433
=> [TASK] Document Includes.rst.txt

Configuration/Sets/MySet/settings.definitions.yaml, Documentation/Reference/ReStructuredText/Code/SiteSettings.rst, Documentation/Reference/ReStructuredText/Code/_siteSetSettings.rst.txt, Documentation/guides.xml
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/716
=> [TASK] Document typo3-site-settings directive

Documentation/Howto/EditOnGithub.rst, Documentation/Maintainers/NewMajorCoreVersion.rst
=> [TASK] Adjust inventory links to their new place

Documentation/Index.rst, Documentation/guides.xml
We always call it this when we are talking about it
=> [TASK] Call How to Document by this name

Documentation/Howto/WritingDocForExtension/Webhook.rst
1. Enhanced the documentation for better readability
2. Added useful webhook testing for developers
=> Improved the documentation formatting and the structure

Documentation/Howto/WritingDocForExtension/Webhook.rst
This is a follow up of PR#483 to clean-up line-length and correct the last few indents to 4 spaces
=> Set line-length to 80. Use 4 spaces indent

Documentation/Howto/EditLocal.rst, Documentation/Howto/RenderingDocs/Index.rst, Documentation/Howto/WritingDocForExtension/Index.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/464
=> [TASK] Improve rendering page

Documentation/Reference/ReStructuredText/Code/Codeblocks.rst
References https://github.com/TYPO3-Documentation/render-guides/issues/974
=> Remove non working literalinclude diff example

Documentation/Reference/ReStructuredText/Code/Codeblocks.rst, Documentation/Reference/ReStructuredText/Code/InlineCode.rst, Documentation/Reference/ReStructuredText/Code/_snippets/_inline-code-languages.rst.txt, Documentation/Reference/ReStructuredText/Code/_snippets/_inline-code.rst.txt, Documentation/Reference/ReStructuredText/Content/Index.rst, Documentation/Reference/ReStructuredText/InlineMarkup/Index.rst, Documentation/Reference/ReStructuredText/InlineMarkup/InlineMarkup/Index.rst, Documentation/Reference/ReStructuredText/InlineMarkup/TextRoles/Index.rst, Documentation/Reference/ReStructuredText/InlineMarkup/TextRoles/_snippets/_text-roles.rst.txt
Move the content away from the mix-up with
the inline-code roles. Link to related elements like links and inline code.
=> [TASK] Create chapter for inline markup
